### ISSUE TITLE
Using Geolocation API to get the users location

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-project-22.JUL.PREP.3#3]
Using the Geolocation API to get the users location as the first weather results displayed, instead of just New York City.

Read more [here](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API).

**Comment by thucvy** [comment]
This is done through PR #14 #26 and #36

**Comment by thucvy** [comment]
Further implementation was done for this issue. Instead of detecting and displaying weather for the current location only on the first time rendering the page, a button to "Use current location' was implemented so that users can always go back and forth between using their current location and searching for a specific city.
